version: "3.4"

services:
  moni:
    image: moni:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "flask init-db && flask run -p 8080 --host 0.0.0.0"
    ports: 
      - 8080:8080
    volumes: 
      - .:/app:cached
